### ISSUE TITLE
EDSR-PyTorch can not be found

### ISSUE THREAD

**Issue by www132409011** [MonashAI/QTool#7]
I want to use the part of super resolution. When download the quantization version of EDSR-PyTorch project. i get:
fatal: repository 'https://github.com/blueardour/EDSR-PyTorch/' not found

**Comment by blueardour** [comment]
The repo is marked as private. Public version refer to https://github.com/billhhh/FQSR

**Comment by blueardour** [comment]
The QTool can act as a plugin to any CNN-based frameworks. Generally, we do not hard code the repo into detector, segmentation or SR projects, but build a symbol link to get refered.
